// Portfolio Data - Gamandeep Singh

export const personalInfo = {
  name: "Gamandeep Singh",
  title: "Full Stack Developer",
  subtitle: "Web3 Enthusiast",
  email: "gamandeepsingh6@gmail.com",
  phone: "+91 6394003592",
  location: "Bengaluru, India",
  portfolio: "https://gamandeepsingh.vercel.app/",
  linkedin: "https://www.linkedin.com/in/gamandeep-singh-344001256/",
  github: "https://github.com/gamandeepsingh",
  twitter: "https://x.com/gamandeepsingh4",
  bio: "A passionate Full Stack Developer with expertise in Web3, building scalable applications with modern technologies. Currently solving complex problems at GPU.Net while leading 250+ members at INNOGEEKS.",
  shortBio: "I craft digital experiences that combine creativity with cutting-edge technology. Specializing in React, Next.js, and Web3 development.",
};

export const education = [
  {
    institution: "KIET Group of Institutions",
    degree: "BTech in CSIT",
    affiliation: "Affiliated to AKTU",
    cgpa: "9 / 10",
    year: "Mar 2026",
    location: "Delhi NCR",
  },
  {
    institution: "S.N. Public School",
    board: "CBSE",
    class12: "95.8%",
    class10: "92.8%",
  },
];

export const experience = [
  {
    id: 1,
    company: "GPU.Net",
    role: "Full Stack Developer",
    logo:"https://imgs.search.brave.com/uZVLTBY2RAap6SqQYRiUUnaYSNVtbpGKvi-HJJzicFQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9taXJv/Lm1lZGl1bS5jb20v/djIvMSpMUUFUNWFu/NlJzVndJX0JnN1ZT/WF9RLmpwZWc",
    type: "Full-time",
    duration: "Oct 2025 – Present",
    technologies: ["React", "Hono", "Next.js", "TypeScript", "Web3", "Ethereum"],
    description: [
      "Built Twitter-like feeds for GPU.Net using Hono, Server-Sent Events (SSE), Redis and Drizzle.",
      "Contributed to the design and scaling of both backend and frontend systems.",
    ],
    link: "https://x.com/gpunet",
  },
  {
    id: 2,
    company: "Credible Finance",
    role: "Full Stack Developer",
    logo:"https://pbs.twimg.com/profile_images/1865768451463335936/WOI6x-2R_400x400.jpg",
    type: "Part-time",
    duration: "Aug 2025 – Oct 2025",
    technologies: ["React", "Next.js", "TypeScript", "Web3", "React Query","Solana"],
    description: [
      "Integrated Web3 wallets and smart contracts with backend APIs.",
      "Designed and developed the entire website to significantly improve user experience (UX).",
    ],
    link: "https://x.com/crediblefin",
  },
  {
    id: 3,
    company: "Decharge Networks",
    logo:"https://decharge.us/favicon.png",
    role: "Web3 Frontend Developer",
    type: "Freelance",
    duration: "Aug 2025 – Oct 2025",
    technologies: ["Solana", "NextJS", "Tanstack", "Zustand", "Solana"],
    description: [
      "Integrated Web3 wallets and Solana smart contracts on the frontend.",
      "Redesigned the complete website to enhance UX and performance.",
    ],
    link: "https://x.com/decharge",
  },
  {
    id: 4,
    company: "Elanine Creatives",
    logo:"https://res.cloudinary.com/dib0peewu/image/upload/v1725112664/Screenshot_from_2024-08-31_19-23-09-removebg-preview_emtywq.png",
    role: "SDE Intern",
    type: "Internship",
    duration: "July 2024 - Sep 2025",
    technologies: ["MERN", "MEAN", "DevOps", "SaaS", "Microservices", "CMS"],
    description: [
      "Shipped 10+ full-stack SaaS projects across multiple domains.",
      "Built FindYourVibe end-to-end, covering architecture, backend, frontend, and microservices.",
      "Developed a custom React-based component library — PRISTINE UI to streamline and standardize UI development."
    ],
    link: "https://elanine.com/",
  },
  {
    id: 5,
    company: "EasyEd",
    role: "Backend Intern",
    logo:"https://pbs.twimg.com/profile_images/1682074886083317761/iepus53m_400x400.jpg",
    type: "Internship",
    duration: "Jan 2024 - June 2024",
    technologies: ["NodeJS", "AWS", "Cloudinary"],
    description: [
      "Improved backend performance by optimizing API response times through effective caching, reducing latency",
    ],
    link: "https://x.com/Easyeduverse",
  },
];

export const skills = {
  languages: ["JavaScript", "Java", "Solidity", "C", "HTML", "TypeScript", "RUST", "Python"],
  frameworks: ["ReactJS", "Angular", "NextJS", "Node", "Express", "Flask", "Tailwind", "SCSS", "GSAP","Anchor"],
  databases: ["MongoDB", "PostgreSQL", "Prisma", "Drizzle ORM"],
  web3: ["Solana.js", "Ethereum", "Web3.js", "Smart Contracts"],
  tools: ["GitHub", "Git", "Docker", "AWS", "Framer", "Postman", "Clerk", "Vercel", "Netlify"],
  others: ["Leetcode (100+)", "GFG (100+)"],
};

export const projectData = [
  {
    id: "gpunet",
    title: "GPU.Net - Decentralized CPU/GPU Sharing",
    subtitle: "Decentralized Cloud Computing",
    description: "Decentralized cloud computing platform enabling users to share and monetize their idle CPU/GPU resources, built with React, Hono, Next.js, TypeScript, Web3, and Ethereum.",
    technologies: ["VITE-SSR", "Solidity", "QR Payments", "Web3"],
    image: "https://res.cloudinary.com/dib0peewu/image/upload/v1771412911/Screenshot_2026-02-18_at_4.38.23_PM_r5eid5.png",
    link: "https://gpu.net/enterprise",
    github: "http://github.com/brahmGAN",
    category: "web3",
    status: "Completed",
    year: "2025",
    slug: { current: "gpunet" },
  },
  {
    id: "chainupi",
    title: "ChainUPI - Multi-Chain Crypto Payments",
    subtitle: "OnGoing",
    description: "Revolutionary multi-chain crypto payment solution enabling seamless QR code payments, real-time crypto conversion with Chainlink, and secure escrow settlement.",
    technologies: ["NextJS", "Solidity", "Chainlink", "QR Payments", "Web3"],
    image: "https://res.cloudinary.com/dib0peewu/image/upload/v1767386640/Screenshot_2026-01-03_021343_bwzena.png",
    link: "https://chainupi.tech",
    github: "https://github.com/ChainUPI",
    category: "web3",
    status: "In Progress",
    year: "2025",
    slug: { current: "chainupi" },
  },
  {
    id: "findyourvibe",
    title: "FindYourVibe - NearBy Events Listing",
    subtitle: "Event Platform",
    description: "MEAN stack (microservice) based event platform with Razorpay integration for ticket purchases and a real-time dashboard to track sales and user activity.",
    technologies: ["Angular", "Express", "MongoDB", "Node.js", "Razorpay"],
    image: "https://res.cloudinary.com/dib0peewu/image/upload/v1746825827/Screenshot_2025-05-10_025321_dvhaqv.png",
    link: "https://findyourvibe.in/",
    github: null,
    category: "web",
    status: "Completed",
    year: "2025",
    slug: { current: "findyourvibe" },
  },
  {
    id: "credible",
    title: "Credible - On-Chain Credit Protocol",
    subtitle: "The First Stablecoin Pay Later Protocol",
    description: "Credible brings on-chain credit to consumers and institutions for fast, borderless payments.",
    technologies: ["NextJS", "TypeScript", "Ethereum", "Web3"],
    image: "https://res.cloudinary.com/dib0peewu/image/upload/v1771413195/Screenshot_2026-02-18_at_4.43.10_PM_v2cwsb.png",
    link: "https://credible.finance/",
    github: null,
    extraLink:"https://x.com/crediblefin",
    category: "web3",
    status: "Completed",
    year: "2025",
    slug: { current: "credible" },
  },
  {
    id: "storenv",
    title: "Storenv - Secure Your env variables",
    subtitle: "Security Tool",
    description: "Built with security and ease of use in mind. Simplifies the process with a secure and centralized solution for managing environment variables.",
    technologies: ["NextJS", "TypeScript", "NextAuth", "CryptoJS", "MongoDB"],
    image: "https://res.cloudinary.com/dib0peewu/image/upload/v1740937701/Screenshot_2025-03-02_231811_dettf6.png",
    link: "https://storenv.vercel.app/",
    github: "https://github.com/gamandeepsingh/Storenv",
    category: "tool",
    status: "Completed",
    year: "2025",
    slug: { current: "storenv" },
  },
  {
    id: "solana-pay-widget",
    title: "Solana Pay Plugin",
    subtitle: "NPM Package",
    description: "TypeScript-based Solana payment widget for seamless integration into web applications.",
    technologies: ["TypeScript", "Solana", "Web3", "Payment Gateway"],
    image: "https://res.cloudinary.com/dib0peewu/image/upload/v1767386754/Screenshot_2026-01-03_021545_mtq2de.png",
    link: "https://www.npmjs.com/package/solana-pay-widget",
    extraLink:"https://medium.com/@gamandeepsingh4/from-stripe-to-solana-why-i-built-a-web3-payment-widget-that-actually-works-8b72b678afa8",
    github: null,
    category: "web3",
    status: "Published",
    year: "2025",
    slug: { current: "solana-pay-widget" },
  },
  {
    id: "decharge",
    title: "Decharge - EV Charging Platform",
    subtitle: "EV Charging Platform",
    description: "Developed a comprehensive EV charging platform featuring user-friendly interfaces for locating and reserving charging stations",
    technologies: ["Solana", "NextJS", "Vite", "Tanstack", "Zustand", "Web3"],
    image: "https://res.cloudinary.com/dib0peewu/image/upload/v1767386715/Screenshot_2026-01-03_021456_xsmfgc.png",
    link: "https://decharge.us/",
    github: null,
    category: "web3",
    status: "Freelance",
    year: "2025",
    extraLink:"https://x.com/decharge",
    slug: { current: "decharge" },
  },
  {
    id: "pristine-ui-library",
    title: "PRISTINE - UI Library",
    subtitle: "Component Library",
    description: "Custom React-based component library to streamline UI development with beautiful, consistent components.",
    technologies: ["ReactJS", "Framer Motion", "Tailwind CSS", "Docusaurus", "mdx"],
    image: "https://res.cloudinary.com/dib0peewu/image/upload/v1746825946/Screenshot_2025-05-10_025532_qbqmgd.png",
    link: "https://pristine-weld.vercel.app/",
    github: null,
    category: "ui",
    status: "Completed",
    year: "2024",
    slug: { current: "pristine-ui-library" },
  },
  {
    id: "jaagran-patra",
    title: "Jaagran Patra - Civic Engagement Platform",
    subtitle: "Civic Platform",
    description: "Platform connecting citizens with local government for reporting issues, accessing services, and community engagement.",
    technologies: ["ReactJS", "Typescript", "Google Maps API", "Zoom SDK", "NodeJS", "Prisma", "Large Datasets", "Multiple Languages"],
    image: "https://res.cloudinary.com/dib0peewu/image/upload/v1767967586/2a182ce8-1797-4e7a-b8a6-e186b1e12699.png",
    link: "https://jaagran-patra.vercel.app/",
    github: null,
    category: "ui",
    status: "Completed",
    year: "2024",
    slug: { current: "pristine-ui-library" },
  },
  {
    id: "listerji",
    title: "Listerji",
    subtitle: "Business Listing Platform",
    description: "Business listing platform with advanced search and filtering capabilities, integrated with Razorpay for premium listings.",
    technologies: ["ReactJS", "Razorpay", "Redis", "ExpressJS"],
    image: "https://res.cloudinary.com/dib0peewu/image/upload/v1740937680/Screenshot_2025-03-02_231711_kpqcwf.png",
    link: "https://www.listerji.com/",
    github: null,
    category: "web",
    status: "Completed",
    year: "2024",
    slug: { current: "listerji" },
  },
  {
    id: "paybursement",
    title: "Paybursement",
    subtitle: "Payroll Tool",
    description: "Payroll management tool with automated salary disbursement and tax calculations, integrated with Razorpay for payments.",
    technologies: ["NextJS", "Razorpay", "Clerk", "MongoDB"],
    image: "https://res.cloudinary.com/dib0peewu/image/upload/v1740937728/Screenshot_2025-03-02_231839_wljvf5.png",
    link: "https://paybursement-frontend.vercel.app/",
    github: "https://github.com/gamandeepsingh/paybursement",
    category: "web",
    status: "Completed",
    year: "2024",
    slug: { current: "paybursement" },
  },
  {
    id: "pristine-mvp",
    title: "PRISTINE MVP",
    subtitle: "Landing Page",
    description: "Modern animated landing page with smooth animations and interactions.",
    technologies: ["ReactJS", "Framer Motion", "GSAP", "Tailwind CSS", "NODEMAILER"],
    image: "https://res.cloudinary.com/dib0peewu/image/upload/v1732798544/ryrynggdgbcag3nokkh0.png",
    link: "https://pristine-weld.vercel.app/",
    github: null,
    category: "web",
    status: "Completed",
    year: "2024",
    slug: { current: "pristine-mvp" },
  },
  {
    id: "payzoll-clone",
    title: "Payzoll Clone - Payment Management",
    subtitle: "Clone Project",
    description: "Modern animated landing page with smooth animations and interactions.",
    technologies: ["ReactJS", "Framer Motion", "GSAP", "Tailwind CSS"],
    image: "https://res.cloudinary.com/dib0peewu/image/upload/v1748687268/Screenshot_2025-05-31_155710_ftel8c.png",
    link: "https://payzoll-six.vercel.app/",
    github: null,
    category: "web",
    status: "Completed",
    year: "2024",
    slug: { current: "payzoll-clone" },
  },
  {
    id: "calendso",
    title: "Calendso",
    subtitle: "Scheduling Tool",
    description: "Calendar scheduling application with Google Calendar API integration.",
    technologies: ["NEXT JS", "React JS", "Clerk", "GCP-Calendar API"],
    image: "https://res.cloudinary.com/dib0peewu/image/upload/v1732811067/mh8w8c1ewzotvormhuoy.png",
    link: "https://calendso-ebon.vercel.app/",
    github: "https://github.com/gamandeepsingh/Calendso",
    category: "web",
    status: "Completed",
    year: "2023",
    slug: { current: "calendso" },
  },
  {
    id: "assets-roster",
    title: "Assets Roster",
    subtitle: "Management Tool",
    description: "Asset management and organization platform with CMS integration.",
    technologies: ["React JS", "Sanity.io", "Management"],
    image: "https://res.cloudinary.com/dib0peewu/image/upload/v1732810856/qtasvipme3hgih7psdwq.png",
    link: "https://www.assetsroster.com/",
    github: null,
    category: "web",
    status: "Completed",
    year: "2023",
    slug: { current: "assets-roster" },
  },
  {
    id: "innogeeks",
    title: "INNOGEEKS",
    subtitle: "Community Website",
    description: "Official website for INNOGEEKS technical community with event listings and member management.",
    technologies: ["ReactJS", "Framer Motion", "Tailwind CSS"],
    image: "https://res.cloudinary.com/dib0peewu/image/upload/v1721902018/Screenshot_from_2024-07-25_15-36-27_c1z2rf.png",
    link: "https://innogeeks.in",
    github: null,
    category: "web",
    status: "Completed",
    year: "2024",
    slug: { current: "innogeeks" },
  },
  {
    id: "saimlds",
    title: "SAIMLDS",
    subtitle: "Community Website",
    description: "Official website for SAIMLDS community organization built with MERN stack.",
    technologies: ["MERN Stack", "FIREBASE", "Node JS", "ExpressJS"],
    image: "https://res.cloudinary.com/dib0peewu/image/upload/v1721902176/Screenshot_from_2024-07-25_15-39-22_vhiera.png",
    link: "https://saimlds.in/",
    github: null,
    category: "web",
    status: "Completed",
    year: "2023",
    slug: { current: "saimlds" },
  },
  {
    id: "dine-me",
    title: "DINE ME",
    subtitle: "Food Platform",
    description: "Restaurant discovery and table booking platform built with MERN stack.",
    technologies: ["MERN Stack"],
    image: "https://res.cloudinary.com/dib0peewu/image/upload/v1721902269/Screenshot_from_2024-07-25_15-40-34_ttfxgh.png",
    link: "https://dineme.vercel.app/",
    github: "https://github.com/gamandeepsingh/Project01",
    category: "web",
    status: "Completed",
    year: "2022",
    slug: { current: "dine-me" },
  },
  {
    id: "portfolio",
    title: "Portfolio",
    subtitle: "Personal Website",
    description: "My old Personal portfolio website with 3D animations and smooth interactions.",
    technologies: ["MERN Stack", "Vanta JS", "GSAP"],
    image: "https://res.cloudinary.com/dib0peewu/image/upload/v1732811266/x0yndhuv6cgj4dq7tnpa.png",
    link: "https://gamandeep.vercel.app/",
    github: "https://github.com/gamandeepsingh/Portfolio",
    category: "web",
    status: "Completed",
    year: "2023",
    slug: { current: "portfolio" },
  },
  {
    id: "ai-video-generator",
    title: "AI Video Generator",
    subtitle: "AI Tool",
    description: "AI-powered video generation tool using computer vision and language models to generate videos for social media.",
    technologies: ["Open CV", "Mystral AI", "ngRok", "Flask"],
    image: "https://res.cloudinary.com/dib0peewu/image/upload/v1746827801/Screenshot_2025-05-10_032616_qdmhjr.png",
    link: null,
    github: "https://github.com/gamandeepsingh/social_media_generator",
    category: "ai",
    status: "Completed",
    year: "2023",
    slug: { current: "ai-video-generator" },
  },
];

export const awards = [
  { year: "2025", title: "Academics (1st Prize)" },
  { year: "2024", title: "Smart India Hackathon (Top 6th Position)" },
  { year: "2023", title: "HackSphere Hackathon (1st Prize)" },
  { year: "2023", title: "Google Solution Challenge (Top 50)" },
];

export const achievements = [
  "Solved 100+ challenging problems on Leetcode",
  "Selected for Solution Challenge 2024 by Google among 4000+ projects",
  "Leading a team of 250+ members at INNOGEEKS",
  "Won 1st position in Hack Sphere Hackathon",
];

export const certifications = [
  {
    title: "FullStack Web Developer",
    issuer: "LinkedIn",
    year: "2024",
    link: "https://drive.google.com/file/d/1k6x2aZVOqKEFupaj1wuS8MGOqcMl49rN/view",
  },
];